"""API tables (SPEC 6.3)

Revision ID: 0002_api_tables
Revises: 0001_baseline
Create Date: 2026-10-03 00:43:43.370096
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = '0002_api_tables'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dash_email_outbox',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'dead')", name='ck_dash_email_outbox_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dash_email_outbox_due', 'dash_email_outbox', ['status', 'next_attempt_at'], unique=False)
    op.create_table('dash_users',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.CheckConstraint("role IN ('trainer', 'admin')", name='ck_dash_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dash_audit_log',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['dash_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dash_audit_log_actor', 'dash_audit_log', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_dash_audit_log_target', 'dash_audit_log', ['target_type', 'target_id'], unique=False)
    op.create_table('dash_password_reset_tokens',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('used_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dash_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_dash_password_reset_tokens_user_id'), 'dash_password_reset_tokens', ['user_id'], unique=False)
    op.create_table('dash_refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('revoked_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('replaced_by_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dash_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_dash_refresh_tokens_family', 'dash_refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_dash_refresh_tokens_user_id'), 'dash_refresh_tokens', ['user_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.CheckConstraint("resolution IS NULL OR resolution IN ('script_changed', 'agent_issue', 'no_action', 'other')", name='ck_review_queue_resolution'),
    sa.CheckConstraint("status IN ('open', 'reviewed', 'dismissed')", name='ck_review_queue_status'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['dash_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['dash_users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_review_queue_status', 'review_queue', ['status', 'updated_at'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(mysql.BIGINT(unsigned=True), 'mariadb').with_variant(mysql.BIGINT(unsigned=True), 'mysql'), nullable=False),
    sa.Column('page', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('utc_timestamp(6)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dash_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_views_user_page', 'saved_views', ['user_id', 'page'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_views_user_page', table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index('ix_review_queue_status', table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_dash_refresh_tokens_user_id'), table_name='dash_refresh_tokens')
    op.drop_index('ix_dash_refresh_tokens_family', table_name='dash_refresh_tokens')
    op.drop_table('dash_refresh_tokens')
    op.drop_index(op.f('ix_dash_password_reset_tokens_user_id'), table_name='dash_password_reset_tokens')
    op.drop_table('dash_password_reset_tokens')
    op.drop_index('ix_dash_audit_log_target', table_name='dash_audit_log')
    op.drop_index('ix_dash_audit_log_actor', table_name='dash_audit_log')
    op.drop_table('dash_audit_log')
    op.drop_table('dash_users')
    op.drop_index('ix_dash_email_outbox_due', table_name='dash_email_outbox')
    op.drop_table('dash_email_outbox')
    # ### end Alembic commands ###
